-- Seed global exercise library (user_id = null = available to all)
INSERT INTO exercise_library (user_id, name, category, equipment) VALUES
-- Upper body
(NULL, 'TRX Face Pulls', 'upper', 'TRX'),
(NULL, 'Band Pull-Aparts', 'upper', 'Resistance Bands'),
(NULL, 'Arm Circles + Shoulder Rolls', 'upper', 'Bodyweight'),
(NULL, 'Barbell Bench Press', 'upper', 'Barbell + Plates'),
(NULL, 'Barbell Bent-Over Row', 'upper', 'Barbell + Plates'),
(NULL, 'Dumbbell Incline Press', 'upper', 'Adjustable Dumbbells'),
(NULL, 'TRX Row (feet elevated)', 'upper', 'TRX'),
(NULL, 'Dumbbell Lateral Raises', 'upper', 'Adjustable Dumbbells'),
(NULL, 'EZ Bar Curl', 'upper', 'EZ Curl Bar'),
(NULL, 'Tricep Pushdowns (band)', 'upper', 'Resistance Bands'),
(NULL, 'Ab Wheel Rollouts', 'core', 'Ab Wheel'),
(NULL, 'TRX Plank Hold', 'core', 'TRX'),
(NULL, 'Band Shoulder Pass-Throughs', 'upper', 'Resistance Bands'),
(NULL, 'Inchworms', 'upper', 'Bodyweight'),
(NULL, 'Dumbbell Farmer''s Carry', 'full', 'Adjustable Dumbbells'),
(NULL, 'TRX Push-Up (feet elevated)', 'upper', 'TRX'),
(NULL, 'Dumbbell Hammer Curls', 'upper', 'Adjustable Dumbbells'),
(NULL, 'Overhead Band Tricep Extension', 'upper', 'Resistance Bands'),
(NULL, 'Medicine Ball Russian Twists', 'core', 'Medicine Ball'),
(NULL, 'TRX Pike', 'core', 'TRX'),
(NULL, 'Dead Bug (bodyweight)', 'core', 'Bodyweight'),
-- Lower body
(NULL, 'Hip Circle Mobilization', 'lower', 'Bodyweight'),
(NULL, 'Band Lateral Walks', 'lower', 'Resistance Bands'),
(NULL, 'Goblet Squat (light KB)', 'lower', 'Kettlebell'),
(NULL, 'Barbell Back Squat', 'lower', 'Barbell + Plates'),
(NULL, 'Romanian Deadlift (barbell)', 'lower', 'Barbell + Plates'),
(NULL, 'Dumbbell Walking Lunges', 'lower', 'Adjustable Dumbbells'),
(NULL, 'TRX Single-Leg Squat', 'lower', 'TRX'),
(NULL, 'Kettlebell Goblet Squat', 'lower', 'Kettlebell'),
(NULL, 'Standing Calf Raises (barbell)', 'lower', 'Barbell + Plates'),
(NULL, 'Balance Disc Single-Leg Stand', 'core', 'Balance Disc'),
-- HIIT
(NULL, 'Kettlebell Swings', 'hiit', 'Kettlebell'),
(NULL, 'TRX Jump Squats', 'hiit', 'TRX'),
(NULL, 'Medicine Ball Slams', 'hiit', 'Medicine Ball'),
(NULL, 'Barbell Clean & Press', 'hiit', 'Barbell + Plates'),
(NULL, 'Band Squat to Row', 'hiit', 'Resistance Bands'),
(NULL, 'Balance Disc Burpees', 'hiit', 'Balance Disc'),
(NULL, 'Barbell Hang Clean', 'hiit', 'Barbell + Plates'),
(NULL, 'TRX Burpee', 'hiit', 'TRX'),
(NULL, 'Kettlebell Goblet Squat Jumps', 'hiit', 'Kettlebell'),
(NULL, 'Medicine Ball Chest Throw (wall)', 'hiit', 'Medicine Ball'),
(NULL, 'Band Sprinter Pull', 'hiit', 'Resistance Bands'),
(NULL, 'TRX Mountain Climbers', 'hiit', 'TRX'),
-- Full body
(NULL, 'TRX Squat + Row Combo', 'full', 'TRX'),
(NULL, 'Deadlift (barbell)', 'full', 'Barbell + Plates'),
(NULL, 'Barbell Overhead Press', 'full', 'Barbell + Plates'),
(NULL, 'Barbell Row', 'full', 'Barbell + Plates');
