-- Add muscle_group to exercise_library for swap recommendations
ALTER TABLE exercise_library ADD COLUMN IF NOT EXISTS muscle_group TEXT;

-- Update existing exercises with muscle groups (primary target)
UPDATE exercise_library SET muscle_group = 'rear delts' WHERE name = 'TRX Face Pulls';
UPDATE exercise_library SET muscle_group = 'rear delts' WHERE name = 'Band Pull-Aparts';
UPDATE exercise_library SET muscle_group = 'shoulders' WHERE name = 'Arm Circles + Shoulder Rolls';
UPDATE exercise_library SET muscle_group = 'chest' WHERE name = 'Barbell Bench Press';
UPDATE exercise_library SET muscle_group = 'back' WHERE name = 'Barbell Bent-Over Row';
UPDATE exercise_library SET muscle_group = 'chest' WHERE name = 'Dumbbell Incline Press';
UPDATE exercise_library SET muscle_group = 'back' WHERE name = 'TRX Row (feet elevated)';
UPDATE exercise_library SET muscle_group = 'shoulders' WHERE name = 'Dumbbell Lateral Raises';
UPDATE exercise_library SET muscle_group = 'biceps' WHERE name = 'EZ Bar Curl';
UPDATE exercise_library SET muscle_group = 'triceps' WHERE name = 'Tricep Pushdowns (band)';
UPDATE exercise_library SET muscle_group = 'core' WHERE name = 'Ab Wheel Rollouts';
UPDATE exercise_library SET muscle_group = 'core' WHERE name = 'TRX Plank Hold';
UPDATE exercise_library SET muscle_group = 'shoulders' WHERE name = 'Band Shoulder Pass-Throughs';
UPDATE exercise_library SET muscle_group = 'core' WHERE name = 'Inchworms';
UPDATE exercise_library SET muscle_group = 'full' WHERE name = 'Dumbbell Farmer''s Carry';
UPDATE exercise_library SET muscle_group = 'chest' WHERE name = 'TRX Push-Up (feet elevated)';
UPDATE exercise_library SET muscle_group = 'biceps' WHERE name = 'Dumbbell Hammer Curls';
UPDATE exercise_library SET muscle_group = 'triceps' WHERE name = 'Overhead Band Tricep Extension';
UPDATE exercise_library SET muscle_group = 'core' WHERE name = 'Medicine Ball Russian Twists';
UPDATE exercise_library SET muscle_group = 'core' WHERE name = 'TRX Pike';
UPDATE exercise_library SET muscle_group = 'core' WHERE name = 'Dead Bug (bodyweight)';
UPDATE exercise_library SET muscle_group = 'hips' WHERE name = 'Hip Circle Mobilization';
UPDATE exercise_library SET muscle_group = 'glutes' WHERE name = 'Band Lateral Walks';
UPDATE exercise_library SET muscle_group = 'quads' WHERE name = 'Goblet Squat (light KB)';
UPDATE exercise_library SET muscle_group = 'quads' WHERE name = 'Barbell Back Squat';
UPDATE exercise_library SET muscle_group = 'hamstrings' WHERE name = 'Romanian Deadlift (barbell)';
UPDATE exercise_library SET muscle_group = 'quads' WHERE name = 'Dumbbell Walking Lunges';
UPDATE exercise_library SET muscle_group = 'quads' WHERE name = 'TRX Single-Leg Squat';
UPDATE exercise_library SET muscle_group = 'quads' WHERE name = 'Kettlebell Goblet Squat';
UPDATE exercise_library SET muscle_group = 'calves' WHERE name = 'Standing Calf Raises (barbell)';
UPDATE exercise_library SET muscle_group = 'core' WHERE name = 'Balance Disc Single-Leg Stand';
UPDATE exercise_library SET muscle_group = 'hips' WHERE name = 'Kettlebell Swings';
UPDATE exercise_library SET muscle_group = 'quads' WHERE name = 'TRX Jump Squats';
UPDATE exercise_library SET muscle_group = 'core' WHERE name = 'Medicine Ball Slams';
UPDATE exercise_library SET muscle_group = 'full' WHERE name = 'Barbell Clean & Press';
UPDATE exercise_library SET muscle_group = 'full' WHERE name = 'Band Squat to Row';
UPDATE exercise_library SET muscle_group = 'full' WHERE name = 'Balance Disc Burpees';
UPDATE exercise_library SET muscle_group = 'full' WHERE name = 'Barbell Hang Clean';
UPDATE exercise_library SET muscle_group = 'full' WHERE name = 'TRX Burpee';
UPDATE exercise_library SET muscle_group = 'quads' WHERE name = 'Kettlebell Goblet Squat Jumps';
UPDATE exercise_library SET muscle_group = 'chest' WHERE name = 'Medicine Ball Chest Throw (wall)';
UPDATE exercise_library SET muscle_group = 'full' WHERE name = 'Band Sprinter Pull';
UPDATE exercise_library SET muscle_group = 'core' WHERE name = 'TRX Mountain Climbers';
UPDATE exercise_library SET muscle_group = 'full' WHERE name = 'TRX Squat + Row Combo';
UPDATE exercise_library SET muscle_group = 'hamstrings' WHERE name = 'Deadlift (barbell)';
UPDATE exercise_library SET muscle_group = 'shoulders' WHERE name = 'Barbell Overhead Press';
UPDATE exercise_library SET muscle_group = 'back' WHERE name = 'Barbell Row';
